/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rar.junk;

import javax.swing.JSlider;

/**
 *
 * @author rvlander
 */
public class Trackbars extends javax.swing.JPanel {

    CVTracking cvt;

    /**
     * Creates new form Trackbars
     */
    public Trackbars(CVTracking c) {
        cvt = c;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSliderHMIN = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        jSliderHMAX = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        jSliderSMIN = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        jSliderSMAX = new javax.swing.JSlider();
        jLabel5 = new javax.swing.JLabel();
        jSliderVMIN = new javax.swing.JSlider();
        jLabel7 = new javax.swing.JLabel();
        jSliderVMAX = new javax.swing.JSlider();

        setLayout(new java.awt.GridLayout(6, 2));

        jLabel1.setText("HUE MIN");
        add(jLabel1);

        jSliderHMIN.setMaximum(256);
        jSliderHMIN.setValue(0);
        jSliderHMIN.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderHMINStateChanged(evt);
            }
        });
        add(jSliderHMIN);

        jLabel2.setText("HUE MAX");
        add(jLabel2);

        jSliderHMAX.setMaximum(256);
        jSliderHMAX.setValue(256);
        jSliderHMAX.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderHMAXStateChanged(evt);
            }
        });
        add(jSliderHMAX);

        jLabel3.setText("SAT MIN");
        add(jLabel3);

        jSliderSMIN.setMaximum(256);
        jSliderSMIN.setValue(0);
        jSliderSMIN.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderSMINStateChanged(evt);
            }
        });
        add(jSliderSMIN);

        jLabel4.setText("SAT MAN");
        add(jLabel4);

        jSliderSMAX.setMaximum(256);
        jSliderSMAX.setValue(256);
        jSliderSMAX.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderSMAXStateChanged(evt);
            }
        });
        add(jSliderSMAX);

        jLabel5.setText("VAL MIN");
        add(jLabel5);

        jSliderVMIN.setMaximum(256);
        jSliderVMIN.setValue(0);
        jSliderVMIN.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderVMINStateChanged(evt);
            }
        });
        add(jSliderVMIN);

        jLabel7.setText("VAL MAX");
        add(jLabel7);

        jSliderVMAX.setMaximum(256);
        jSliderVMAX.setValue(256);
        jSliderVMAX.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderVMAXStateChanged(evt);
            }
        });
        add(jSliderVMAX);
    }// </editor-fold>//GEN-END:initComponents

    private void jSliderHMINStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderHMINStateChanged
        JSlider js = ((JSlider) evt.getSource());
        cvt.H_MIN = js.getValue();
    }//GEN-LAST:event_jSliderHMINStateChanged

    private void jSliderHMAXStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderHMAXStateChanged
        JSlider js = ((JSlider) evt.getSource());
        cvt.H_MAX = js.getValue();
    }//GEN-LAST:event_jSliderHMAXStateChanged

    private void jSliderSMINStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderSMINStateChanged
        JSlider js = ((JSlider) evt.getSource());
        cvt.S_MIN = js.getValue();
    }//GEN-LAST:event_jSliderSMINStateChanged

    private void jSliderSMAXStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderSMAXStateChanged
        JSlider js = ((JSlider) evt.getSource());
        cvt.S_MAX = js.getValue();
    }//GEN-LAST:event_jSliderSMAXStateChanged

    private void jSliderVMINStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderVMINStateChanged
        JSlider js = ((JSlider) evt.getSource());
        cvt.V_MIN = js.getValue();
    }//GEN-LAST:event_jSliderVMINStateChanged

    private void jSliderVMAXStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderVMAXStateChanged
        JSlider js = ((JSlider) evt.getSource());
        cvt.V_MAX = js.getValue();
    }//GEN-LAST:event_jSliderVMAXStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSlider jSliderHMAX;
    private javax.swing.JSlider jSliderHMIN;
    private javax.swing.JSlider jSliderSMAX;
    private javax.swing.JSlider jSliderSMIN;
    private javax.swing.JSlider jSliderVMAX;
    private javax.swing.JSlider jSliderVMIN;
    // End of variables declaration//GEN-END:variables
}
